project:
  template: 'python_jobs'

values:
  name: 'ceilometer'
  disabled: 'false'
  github_org: 'stackforge'
  review_site: 'review.openstack.org'
  publisher_site: 'TODO.stackforge.org'
  tarball_project: 'ceilometer'
  doc_publisher_site: 'TODO.stackforge.org'
  node: 'oneiric'

---
# python26-essex-gate
main:
  name: 'gate-ceilometer-python26-essex'
  review_site: 'review.openstack.org'
  github_org: 'stackforge'
  project: 'ceilometer'
  authenticatedBuild: 'false'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - python26_essex

scm:
  scm: 'false'

assignednode:
  node: 'oneiric'

---
# python27-essex-gate
main:
  name: 'gate-ceilometer-python27-essex'
  review_site: 'review.openstack.org'
  github_org: 'stackforge'
  project: 'ceilometer'
  authenticatedBuild: 'false'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - python27_essex

scm:
  scm: 'false'

assignednode:
  node: 'oneiric'
