---
# merge-gate
main:
  name: 'gate-devstack-gate-merge'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'devstack-gate'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: 'precise'

