project:
  template: 'python_jobs'

values:
  name: 'python-swiftclient'
  disabled: 'false'
  github_org: 'openstack'
  review_site: 'review.openstack.org'
  publisher_site: 'swift.openstack.org'
  tarball_project: 'swift'
  doc_publisher_site: 'docs.openstack.org'
  node: 'precise'

---
# pypi-upload
main:
  name: 'python-swiftclient-pypi'
  review_site: 'review.openstack.org'
  github_org: 'openstack'
  project: 'python-swiftclient'
  authenticatedBuild: 'false'
  concurrent: 'true'

triggers:
  - zuul_post

builders:
  - gerrit_git_prep
  - shell: tox -v -evenv python setup.py sdist upload

scm:
  scm: 'false'

assignednode:
  node: 'pypi'
