---
main:
  name: 'gate-MRaaS-merge'
  github_org: 'stackforge'
  review_site: 'review.stackforge.org'
  project: 'MRaaS'
  authenticatedBuild: 'true'

triggers:
  - gerrit:
      triggerOnPatchsetUploadedEvent: 'false'
      triggerOnChangeMergedEvent: 'false'
      triggerOnCommentAddedEvent: 'true'
      triggerOnRefUpdatedEvent: 'false'
      triggerApprovalCategory: 'APRV'
      triggerApprovalValue: 1
      failureMessage: 'This change was unable to be automatically merged with the current state of the repository. Please rebase your change and upload a new patchset.'
      projects:
        - projectCompareType: 'PLAIN'
          projectPattern: 'stackforge/MRaaS'
          branchCompareType: 'ANT'
          branchPattern: '**'

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: 'oneiric'

---
main:
  name: 'check-MRaaS-merge'
  github_org: 'stackforge'
  review_site: 'review.stackforge.org'
  project: 'MRaaS'
  authenticatedBuild: 'true'

triggers:
  - gerrit:
      triggerOnPatchsetUploadedEvent: 'true'
      triggerOnChangeMergedEvent: 'false'
      triggerOnCommentAddedEvent: 'false'
      triggerOnRefUpdatedEvent: 'false'
      overrideVotes: 'true'
      gerritBuildSuccessfulVerifiedValue: 1
      gerritBuildFailedVerifiedValue: -1
      failureMessage: 'This change was unable to be automatically merged with the current state of the repository. Please rebase your change and upload a new patchset.'
      projects:
        - projectCompareType: 'PLAIN'
          projectPattern: 'stackforge/MRaaS'
          branchCompareType: 'ANT'
          branchPattern: '**'

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: 'oneiric'
